### PR TITLE
Update Wasmtime to 0.27

### PR DESCRIPTION
**Pull request by enjhnsn2**
This pull request is intended to bring Veracruz up to Wasmtime 0.27 (recent as of ~end of march). 
Wasmtime 0.27 is 1 release behind upstream Wasmtime, but from what I can tell, 0.27 is the last branch that works with rustc 1.45..0-nightly (which Veracruz is bound to).
Among the many improvements that this update will provide are (1) AOT compilation for Wasmtime, (2) the latest security patches, and (3) improved ARM backend support.

There will be an associated pull request to the main Veracruz repo as well with minor api changes to the execution engine so that it can be compatible with the newest Wasmtime.

### CODE REVIEW

**Comment by ShaleXIONG** [comment]
Did you try swap in this version in veracruz and try to compile it?

**Comment by enjhnsn2** [comment]
> Did you try swap in this version in veracruz and try to compile it?

Yes, assuming https://github.com/veracruz-project/veracruz/pull/167 is pulled into the main Veracuz repo, then it builds and runs correctly.

**Review by ShaleXIONG — APPROVED** [review]

**Comment by dominic-mulligan-arm** [comment]
@ShaleXIONG go ahead and merge these two related change sets if you're happy.

**Comment by dominic-mulligan-arm** [comment]
@enjhnsn2 please open a new PR for this: this was merged then reverted pending the intermediate PR that was discussed in the meeting on Thursday.

**Pull request merged**
